version: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn lint
      # - run: yarn test

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "6b:8b:76:03:e9:85:b5:40:dd:a3:db:ef:51:f8:fe:f3"

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build
              git init
              git config user.name "Devseed-CI"
              git config user.email "dev@developmentseed.org"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi